name: .NET Solution Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Test/Test.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet packages
        run: dotnet restore Test_3/Test_3.sln

      - name: Build solution with detailed logging
        run: dotnet build Test/Test.sln -c Release -v:diag

      - name: Run unit tests with code coverage
        run: |
          dotnet test Test/Test.sln -c Release --collect:"Code Coverage"
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet reportgenerator -reports:Test/coverage.cobertura.xml -targetdir:Test/coverage -reporttypes:Cobertura

      - name: Generate test reports (optional)
        run: |
          dotnet reportgenerator -reports:Test/coverage.cobertura.xml -targetdir:Test/coverage -reporttypes:Html
          dotnet reportgenerator -reports:Test/coverage.cobertura.xml -targetdir:Test/coverage -reporttypes:Xml

      - name: Error handling and notification mechanisms
        run: |
          # Example for error notifications
          # Insert specific error handling and notification logic here
