name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Test.sln  # Ensure this is correct
      Test_Project_Path: Test/Test/Test.csproj  # Ensure this is the correct path

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 4.7.2  # Change this based on your project's .NET version

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Verify Solution File Exists
      run: |
        if (!(Test-Path "$env:Solution_Name")) {
          Write-Host "Error: Solution file not found: $env:Solution_Name"
          exit 1
        }

    - name: Restore Dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build Solution
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }}

    - name: Run Unit Tests
      run: dotnet test $env:Test_Project_Path --no-restore --configuration ${{ matrix.configuration }} --verbosity normal
